# Generated by Django 5.1.4 on 2025-04-29 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareholderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_number', models.CharField(max_length=100)),
                ('profile_picture', models.ImageField(upload_to='shareholders/')),
                ('lease_history', models.JSONField(default=list)),
                ('payment_history', models.JSONField(default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shareholder_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
